[package]
name = "sdbms"
version = "0.1.0"
edition = "2024"

[dependencies]
axum="0.7"
tokio={version="1",features=["full"]}
serde={version="1",features=["derive"]}
serde_json="1"
arangors="0.5"
uuid={version="1",features=["v4"]}
dotenv="0.15"
